services:
  database:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: animation_app
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: dev_password_123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck: # Add this for better reliability
      test: ['CMD-SHELL', 'pg_isready -U app_user -d animation_app']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
